server:
  port: 8082

spring:
  application:
    name: score-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/java_learn?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.onycom.score.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.onycom.score.mapper: debug
